/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amortizationsystem.View;

import amortizationsystem.Controller.GUIController;
import java.util.ArrayList;
//import javafx.beans.Observable;

/**
 *
 * @author aleja
 */
public class ViewGetUserGUI extends javax.swing.JFrame implements GUIObservable {
    boolean accept = false;
    ArrayList<GUIController> observers = new ArrayList<GUIController>();
    
    /**
     * Creates new form ViewGetUserGUI
     */
    public ViewGetUserGUI() {
        initComponents();
        this.LoanCurrencyColons.setActionCommand("Colones");
        this.LoanCurrencyDollars.setActionCommand("Dollars");
        this.LoanTypeAmerican.setActionCommand("American");
        this.LoanTypeFrench.setActionCommand("French");
        this.LoanTypeGerman.setActionCommand("German");
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loanType = new javax.swing.ButtonGroup();
        loanCurrency = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoanTypeGerman = new javax.swing.JRadioButton();
        LoanTypeFrench = new javax.swing.JRadioButton();
        LoanTypeAmerican = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inputClientName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputAmount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputTerm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        LoanCurrencyDollars = new javax.swing.JRadioButton();
        LoanCurrencyColons = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        inputAnualIntrestRate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Prestamo");

        jLabel2.setText("Sisema de Consulta");

        loanType.add(LoanTypeGerman);
        LoanTypeGerman.setText("Aleman");
        LoanTypeGerman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanTypeGermanActionPerformed(evt);
            }
        });

        loanType.add(LoanTypeFrench);
        LoanTypeFrench.setText("Frances");
        LoanTypeFrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanTypeFrenchActionPerformed(evt);
            }
        });

        loanType.add(LoanTypeAmerican);
        LoanTypeAmerican.setText("Americano");
        LoanTypeAmerican.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanTypeAmericanActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de Amortizacion Deseada");

        jLabel4.setText("Nombre del Cliente");

        jLabel5.setText("Monto");

        jLabel6.setText("Plazo");

        jLabel7.setText("Moneda");

        loanCurrency.add(LoanCurrencyDollars);
        LoanCurrencyDollars.setText("Dolares");
        LoanCurrencyDollars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanCurrencyDollarsActionPerformed(evt);
            }
        });

        loanCurrency.add(LoanCurrencyColons);
        LoanCurrencyColons.setText("Colones");
        LoanCurrencyColons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanCurrencyColonsActionPerformed(evt);
            }
        });

        jLabel8.setText("Interés Anual");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LoanCurrencyDollars)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LoanCurrencyColons))
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LoanTypeGerman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoanTypeFrench)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoanTypeAmerican))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(inputAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(inputTerm, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputAnualIntrestRate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputClientName)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputAnualIntrestRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoanTypeGerman)
                    .addComponent(LoanTypeFrench)
                    .addComponent(LoanTypeAmerican))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoanCurrencyDollars)
                    .addComponent(LoanCurrencyColons))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoanTypeGermanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanTypeGermanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoanTypeGermanActionPerformed

    private void LoanTypeFrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanTypeFrenchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoanTypeFrenchActionPerformed

    private void LoanTypeAmericanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanTypeAmericanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoanTypeAmericanActionPerformed

    private void LoanCurrencyDollarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanCurrencyDollarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoanCurrencyDollarsActionPerformed

    private void LoanCurrencyColonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanCurrencyColonsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoanCurrencyColonsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        notifyObservers();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGetUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGetUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGetUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGetUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewGetUserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton LoanCurrencyColons;
    private javax.swing.JRadioButton LoanCurrencyDollars;
    private javax.swing.JRadioButton LoanTypeAmerican;
    private javax.swing.JRadioButton LoanTypeFrench;
    private javax.swing.JRadioButton LoanTypeGerman;
    private javax.swing.JTextField inputAmount;
    private javax.swing.JTextField inputAnualIntrestRate;
    private javax.swing.JTextField inputClientName;
    private javax.swing.JTextField inputTerm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.ButtonGroup loanCurrency;
    private javax.swing.ButtonGroup loanType;
    // End of variables declaration//GEN-END:variables

    @Override
    public ArrayList<String> getValues() {
        ArrayList<String> values = new ArrayList<>();
        values.add(this.inputClientName.getText());
        values.add(this.inputAmount.getText());
        values.add(this.inputTerm.getText());
        values.add(this.inputAnualIntrestRate.getText());
        values.add(this.loanType.getSelection().getActionCommand());
        values.add(this.loanCurrency.getSelection().getActionCommand());
        return values;
    }
    @Override
    public void registerObserver(GUIController newController){
        this.observers.add(newController);
    }
    
    @Override
    public void notifyObservers(){
        for(GUIController observer :observers ){
            observer.infoReceived(this);
        }
    }
}
